enabled = "yes"

[settings]
url_prefix = "/admin"
#subdomain = ""
#url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/static/admin"
#root_path = ""
#cli_group = ""

[session]
#admin_session = "yes"
